version: '3.8'

services:
  app:
    build: .
    container_name: speed_app
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: speed
      POSTGRES_PASSWORD: speed
      POSTGRES_DB: speed_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: speed_postgres
    environment:
      POSTGRES_USER: speed
      POSTGRES_PASSWORD: speed
      POSTGRES_DB: speed_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 