version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: speed_postgres
    environment:
      POSTGRES_USER: speed
      POSTGRES_PASSWORD: speed
      POSTGRES_DB: speed_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - dragonflydata:/data
    command: ["--requirepass", "speed"]

  mongodb:
    image: mongo:7
    container_name: speed_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  postgres_data: 
  dragonflydata:
  mongodb_data:
