version: 2.1

# Define reusable executors
executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

# Define reusable commands
commands:
  setup-environment:
    description: "Set up Python environment using Makefile pattern"
    steps:
      - checkout
      - run:
          name: Set up virtual environment
          command: |
            make venv
            # Ensure conflicting SQLAlchemy stubs are removed
            . speed-venv/bin/activate && pip uninstall -y types-SQLAlchemy types-Flask-SQLAlchemy sqlalchemy-stubs sqlalchemy2-stubs || true



# Define jobs
jobs:
  lint:
    executor: python-executor
    steps:
      - setup-environment
      - run:
          name: Run flake8 linting
          command: |
            echo "Running flake8..."
            make lint app
      - run:
          name: Run black formatting check
          command: |
            echo "Running black check..."
            make fmt-check app

  type-check:
    executor: python-executor
    steps:
      - setup-environment
      - run:
          name: Run mypy type checking
          command: |
            echo "Running mypy type checking..."
            make check app

  test:
    executor: python-executor
    steps:
      - setup-environment
      - run:
          name: Run tests
          command: |
            # Add your test command here when you have tests
            # make test
            echo "No tests defined yet - placeholder for future tests"

# Define workflows
workflows:
  version: 2
  ci:
    jobs:
      - lint
      - type-check
      - test:
          requires:
            - lint
            - type-check